In [70]:
import os, time
import openai
import pandas as pd
import base64
import tqdm
from tqdm import tqdm
import pandas as pd
import numpy as np
import random 


In [71]:
cred_path = "../../../Desktop/others/anlp_project/openaikey.txt"
image_path = "data/pic.png"

In [72]:
with open(cred_path, encoding = 'utf-8') as f:
  key = f.readline().strip()

openai.api_key = key

In [73]:
# Function to encode the image
def encode_image(image_path):
  with open(image_path, "rb") as image_file:
    return base64.b64encode(image_file.read()).decode('utf-8')

# Getting the base64 string
base64_image = encode_image(image_path)

In [5]:
def generate_text(temp, top_p):
    response = openai.ChatCompletion.create(
        model="gpt-4-vision-preview",
        temperature = temp,
        top_p = top_p,
        messages=[
        {
            "role": "user",
            "content": [
            {
                "type": "text", 
                "text": "What’s in this image?"
            },
            {
                "type": "image_url", 
                "image_url": {
                "url": f"data:image/jpeg;base64,{base64_image}"}
            }
            ],
        }
        ],
        max_tokens=300,
    )

    # col = [i]
    data = {"temperature" : [temp],
            "top_p" : [top_p],
           "description": response.choices[0]["message"]["content"]
           }
    
    df = pd.DataFrame(data)

    return df
    #return response.choices[0]["message"]["content"]


In [35]:
def get_description_df(param_list, temp):
  df = pd.DataFrame()
  for i in tqdm(param_list):
    # new = generate_text(temp=i, top_p=top_p)
    new = generate_text(temp=temp, top_p=i)
    df = pd.concat([df, new])
  df = df.reset_index(drop=True)
  return df

In [113]:
# temps = np.arange(0.001, 1.001, 0.001)
# tempsplit = np.array_split(temps, 20)

In [26]:
topps = np.arange(0.001, 1.001, 0.001)
toppsplit = np.array_split(topps, 200)
# tempsplit[111:]
toppsplit[-1]

array([0.996, 0.997, 0.998, 0.999, 1.   ])

In [ ]:
# temps = np.arange(0.001, 1.001, 0.001)
# tempsplit = np.array_split(temps, 200)
# tempsplit[111:]

In [ ]:
for idx, topp in enumerate(toppsplit):
    print(idx, topp)

In [39]:
for idx, topp in enumerate(toppsplit[113:]):
    print(idx, topp)
    df_continue = get_description_df(param_list=topp, temp=1)
    topp_name = str(np.round(topp[-1], decimals=3))
    df_continue.to_pickle('data/topp_data_4v/df_'+topp_name+'.pkl')

0 [0.566 0.567 0.568 0.569 0.57 ]


100%|██████████| 5/5 [00:22<00:00,  4.49s/it]


1 [0.571 0.572 0.573 0.574 0.575]


100%|██████████| 5/5 [00:24<00:00,  4.86s/it]


2 [0.576 0.577 0.578 0.579 0.58 ]


100%|██████████| 5/5 [00:31<00:00,  6.32s/it]


3 [0.581 0.582 0.583 0.584 0.585]


100%|██████████| 5/5 [00:21<00:00,  4.28s/it]


4 [0.586 0.587 0.588 0.589 0.59 ]


100%|██████████| 5/5 [00:45<00:00,  9.09s/it]


5 [0.591 0.592 0.593 0.594 0.595]


100%|██████████| 5/5 [00:20<00:00,  4.19s/it]


6 [0.596 0.597 0.598 0.599 0.6  ]


100%|██████████| 5/5 [00:37<00:00,  7.53s/it]


7 [0.601 0.602 0.603 0.604 0.605]


100%|██████████| 5/5 [00:22<00:00,  4.50s/it]


8 [0.606 0.607 0.608 0.609 0.61 ]


100%|██████████| 5/5 [00:25<00:00,  5.02s/it]


9 [0.611 0.612 0.613 0.614 0.615]


100%|██████████| 5/5 [00:29<00:00,  5.88s/it]


10 [0.616 0.617 0.618 0.619 0.62 ]


100%|██████████| 5/5 [00:28<00:00,  5.61s/it]


11 [0.621 0.622 0.623 0.624 0.625]


100%|██████████| 5/5 [00:23<00:00,  4.75s/it]


12 [0.626 0.627 0.628 0.629 0.63 ]


100%|██████████| 5/5 [00:29<00:00,  5.95s/it]


13 [0.631 0.632 0.633 0.634 0.635]


100%|██████████| 5/5 [00:25<00:00,  5.12s/it]


14 [0.636 0.637 0.638 0.639 0.64 ]


100%|██████████| 5/5 [00:31<00:00,  6.26s/it]


15 [0.641 0.642 0.643 0.644 0.645]


100%|██████████| 5/5 [00:26<00:00,  5.35s/it]


16 [0.646 0.647 0.648 0.649 0.65 ]


100%|██████████| 5/5 [00:31<00:00,  6.37s/it]


17 [0.651 0.652 0.653 0.654 0.655]


100%|██████████| 5/5 [00:31<00:00,  6.26s/it]


18 [0.656 0.657 0.658 0.659 0.66 ]


100%|██████████| 5/5 [00:28<00:00,  5.64s/it]


19 [0.661 0.662 0.663 0.664 0.665]


100%|██████████| 5/5 [00:29<00:00,  5.90s/it]


20 [0.666 0.667 0.668 0.669 0.67 ]


100%|██████████| 5/5 [00:31<00:00,  6.30s/it]


21 [0.671 0.672 0.673 0.674 0.675]


100%|██████████| 5/5 [00:27<00:00,  5.49s/it]


22 [0.676 0.677 0.678 0.679 0.68 ]


100%|██████████| 5/5 [00:23<00:00,  4.76s/it]


23 [0.681 0.682 0.683 0.684 0.685]


100%|██████████| 5/5 [00:25<00:00,  5.19s/it]


24 [0.686 0.687 0.688 0.689 0.69 ]


100%|██████████| 5/5 [00:29<00:00,  5.81s/it]


25 [0.691 0.692 0.693 0.694 0.695]


100%|██████████| 5/5 [00:36<00:00,  7.26s/it]


26 [0.696 0.697 0.698 0.699 0.7  ]


100%|██████████| 5/5 [00:22<00:00,  4.40s/it]


27 [0.701 0.702 0.703 0.704 0.705]


100%|██████████| 5/5 [00:27<00:00,  5.55s/it]


28 [0.706 0.707 0.708 0.709 0.71 ]


100%|██████████| 5/5 [00:27<00:00,  5.58s/it]


29 [0.711 0.712 0.713 0.714 0.715]


100%|██████████| 5/5 [00:27<00:00,  5.60s/it]


30 [0.716 0.717 0.718 0.719 0.72 ]


100%|██████████| 5/5 [00:25<00:00,  5.17s/it]


31 [0.721 0.722 0.723 0.724 0.725]


100%|██████████| 5/5 [00:28<00:00,  5.69s/it]


32 [0.726 0.727 0.728 0.729 0.73 ]


100%|██████████| 5/5 [00:39<00:00,  7.89s/it]


33 [0.731 0.732 0.733 0.734 0.735]


100%|██████████| 5/5 [00:22<00:00,  4.60s/it]


34 [0.736 0.737 0.738 0.739 0.74 ]


100%|██████████| 5/5 [00:22<00:00,  4.41s/it]


35 [0.741 0.742 0.743 0.744 0.745]


100%|██████████| 5/5 [00:36<00:00,  7.27s/it]


36 [0.746 0.747 0.748 0.749 0.75 ]


100%|██████████| 5/5 [00:25<00:00,  5.15s/it]


37 [0.751 0.752 0.753 0.754 0.755]


100%|██████████| 5/5 [00:22<00:00,  4.58s/it]


38 [0.756 0.757 0.758 0.759 0.76 ]


100%|██████████| 5/5 [00:27<00:00,  5.42s/it]


39 [0.761 0.762 0.763 0.764 0.765]


100%|██████████| 5/5 [00:23<00:00,  4.74s/it]


40 [0.766 0.767 0.768 0.769 0.77 ]


100%|██████████| 5/5 [00:26<00:00,  5.21s/it]


41 [0.771 0.772 0.773 0.774 0.775]


100%|██████████| 5/5 [00:32<00:00,  6.41s/it]


42 [0.776 0.777 0.778 0.779 0.78 ]


100%|██████████| 5/5 [00:23<00:00,  4.65s/it]


43 [0.781 0.782 0.783 0.784 0.785]


100%|██████████| 5/5 [00:22<00:00,  4.53s/it]


44 [0.786 0.787 0.788 0.789 0.79 ]


100%|██████████| 5/5 [00:21<00:00,  4.38s/it]


45 [0.791 0.792 0.793 0.794 0.795]


100%|██████████| 5/5 [00:30<00:00,  6.11s/it]


46 [0.796 0.797 0.798 0.799 0.8  ]


100%|██████████| 5/5 [00:26<00:00,  5.32s/it]


47 [0.801 0.802 0.803 0.804 0.805]


100%|██████████| 5/5 [00:21<00:00,  4.38s/it]


48 [0.806 0.807 0.808 0.809 0.81 ]


100%|██████████| 5/5 [00:21<00:00,  4.35s/it]


49 [0.811 0.812 0.813 0.814 0.815]


100%|██████████| 5/5 [00:23<00:00,  4.75s/it]


50 [0.816 0.817 0.818 0.819 0.82 ]


100%|██████████| 5/5 [00:25<00:00,  5.18s/it]


51 [0.821 0.822 0.823 0.824 0.825]


100%|██████████| 5/5 [00:24<00:00,  4.95s/it]


52 [0.826 0.827 0.828 0.829 0.83 ]


100%|██████████| 5/5 [00:27<00:00,  5.47s/it]


53 [0.831 0.832 0.833 0.834 0.835]


100%|██████████| 5/5 [00:22<00:00,  4.50s/it]


54 [0.836 0.837 0.838 0.839 0.84 ]


100%|██████████| 5/5 [00:24<00:00,  4.85s/it]


55 [0.841 0.842 0.843 0.844 0.845]


100%|██████████| 5/5 [00:27<00:00,  5.46s/it]


56 [0.846 0.847 0.848 0.849 0.85 ]


100%|██████████| 5/5 [00:25<00:00,  5.03s/it]


57 [0.851 0.852 0.853 0.854 0.855]


100%|██████████| 5/5 [00:22<00:00,  4.40s/it]


58 [0.856 0.857 0.858 0.859 0.86 ]


100%|██████████| 5/5 [00:31<00:00,  6.32s/it]


59 [0.861 0.862 0.863 0.864 0.865]


100%|██████████| 5/5 [00:33<00:00,  6.76s/it]


60 [0.866 0.867 0.868 0.869 0.87 ]


100%|██████████| 5/5 [00:26<00:00,  5.28s/it]


61 [0.871 0.872 0.873 0.874 0.875]


100%|██████████| 5/5 [00:38<00:00,  7.76s/it]


62 [0.876 0.877 0.878 0.879 0.88 ]


100%|██████████| 5/5 [00:28<00:00,  5.67s/it]


63 [0.881 0.882 0.883 0.884 0.885]


100%|██████████| 5/5 [00:28<00:00,  5.65s/it]


64 [0.886 0.887 0.888 0.889 0.89 ]


100%|██████████| 5/5 [00:27<00:00,  5.47s/it]


65 [0.891 0.892 0.893 0.894 0.895]


100%|██████████| 5/5 [00:32<00:00,  6.43s/it]


66 [0.896 0.897 0.898 0.899 0.9  ]


100%|██████████| 5/5 [00:26<00:00,  5.33s/it]


67 [0.901 0.902 0.903 0.904 0.905]


100%|██████████| 5/5 [00:21<00:00,  4.36s/it]


68 [0.906 0.907 0.908 0.909 0.91 ]


100%|██████████| 5/5 [00:28<00:00,  5.78s/it]


69 [0.911 0.912 0.913 0.914 0.915]


100%|██████████| 5/5 [00:24<00:00,  4.91s/it]


70 [0.916 0.917 0.918 0.919 0.92 ]


100%|██████████| 5/5 [00:21<00:00,  4.36s/it]


71 [0.921 0.922 0.923 0.924 0.925]


100%|██████████| 5/5 [00:28<00:00,  5.67s/it]


72 [0.926 0.927 0.928 0.929 0.93 ]


100%|██████████| 5/5 [00:24<00:00,  4.80s/it]


73 [0.931 0.932 0.933 0.934 0.935]


100%|██████████| 5/5 [00:31<00:00,  6.34s/it]


74 [0.936 0.937 0.938 0.939 0.94 ]


100%|██████████| 5/5 [00:21<00:00,  4.35s/it]


75 [0.941 0.942 0.943 0.944 0.945]


100%|██████████| 5/5 [00:29<00:00,  5.97s/it]


76 [0.946 0.947 0.948 0.949 0.95 ]


100%|██████████| 5/5 [00:22<00:00,  4.41s/it]


77 [0.951 0.952 0.953 0.954 0.955]


100%|██████████| 5/5 [00:27<00:00,  5.54s/it]


78 [0.956 0.957 0.958 0.959 0.96 ]


100%|██████████| 5/5 [00:25<00:00,  5.10s/it]


79 [0.961 0.962 0.963 0.964 0.965]


100%|██████████| 5/5 [00:26<00:00,  5.34s/it]


80 [0.966 0.967 0.968 0.969 0.97 ]


100%|██████████| 5/5 [00:24<00:00,  4.83s/it]


81 [0.971 0.972 0.973 0.974 0.975]


100%|██████████| 5/5 [00:21<00:00,  4.24s/it]


82 [0.976 0.977 0.978 0.979 0.98 ]


100%|██████████| 5/5 [00:22<00:00,  4.40s/it]


83 [0.981 0.982 0.983 0.984 0.985]


100%|██████████| 5/5 [00:30<00:00,  6.18s/it]


84 [0.986 0.987 0.988 0.989 0.99 ]


100%|██████████| 5/5 [00:34<00:00,  6.85s/it]


85 [0.991 0.992 0.993 0.994 0.995]


100%|██████████| 5/5 [00:31<00:00,  6.28s/it]


86 [0.996 0.997 0.998 0.999 1.   ]


100%|██████████| 5/5 [00:24<00:00,  4.89s/it]


In [9]:
for temp in tempsplit[112:]:
    print(temp)
    df_continue = get_description_df(param_list=temp, top_p=1)
    temp_name = str(np.round(temp[-1], decimals=3))
    df_continue.to_pickle('data/temp_data_4v/df_'+temp_name+'.pkl')

[0.561 0.562 0.563 0.564 0.565]


100%|██████████| 5/5 [00:31<00:00,  6.39s/it]


[0.566 0.567 0.568 0.569 0.57 ]


100%|██████████| 5/5 [00:33<00:00,  6.79s/it]


[0.571 0.572 0.573 0.574 0.575]


100%|██████████| 5/5 [00:36<00:00,  7.35s/it]


[0.576 0.577 0.578 0.579 0.58 ]


100%|██████████| 5/5 [00:25<00:00,  5.18s/it]


[0.581 0.582 0.583 0.584 0.585]


100%|██████████| 5/5 [00:27<00:00,  5.55s/it]


[0.586 0.587 0.588 0.589 0.59 ]


100%|██████████| 5/5 [00:28<00:00,  5.71s/it]


[0.591 0.592 0.593 0.594 0.595]


100%|██████████| 5/5 [00:34<00:00,  6.86s/it]


[0.596 0.597 0.598 0.599 0.6  ]


100%|██████████| 5/5 [00:26<00:00,  5.24s/it]


[0.601 0.602 0.603 0.604 0.605]


100%|██████████| 5/5 [00:36<00:00,  7.30s/it]


[0.606 0.607 0.608 0.609 0.61 ]


100%|██████████| 5/5 [00:28<00:00,  5.68s/it]


[0.611 0.612 0.613 0.614 0.615]


100%|██████████| 5/5 [00:36<00:00,  7.31s/it]


[0.616 0.617 0.618 0.619 0.62 ]


100%|██████████| 5/5 [00:27<00:00,  5.48s/it]


[0.621 0.622 0.623 0.624 0.625]


100%|██████████| 5/5 [00:30<00:00,  6.04s/it]


[0.626 0.627 0.628 0.629 0.63 ]


100%|██████████| 5/5 [00:31<00:00,  6.21s/it]


[0.631 0.632 0.633 0.634 0.635]


100%|██████████| 5/5 [00:22<00:00,  4.48s/it]


[0.636 0.637 0.638 0.639 0.64 ]


100%|██████████| 5/5 [00:23<00:00,  4.64s/it]


[0.641 0.642 0.643 0.644 0.645]


100%|██████████| 5/5 [00:26<00:00,  5.29s/it]


[0.646 0.647 0.648 0.649 0.65 ]


100%|██████████| 5/5 [00:31<00:00,  6.28s/it]


[0.651 0.652 0.653 0.654 0.655]


100%|██████████| 5/5 [00:33<00:00,  6.60s/it]


[0.656 0.657 0.658 0.659 0.66 ]


100%|██████████| 5/5 [00:25<00:00,  5.04s/it]


[0.661 0.662 0.663 0.664 0.665]


100%|██████████| 5/5 [00:25<00:00,  5.10s/it]


[0.666 0.667 0.668 0.669 0.67 ]


100%|██████████| 5/5 [00:29<00:00,  5.80s/it]


[0.671 0.672 0.673 0.674 0.675]


100%|██████████| 5/5 [00:32<00:00,  6.42s/it]


[0.676 0.677 0.678 0.679 0.68 ]


100%|██████████| 5/5 [00:29<00:00,  5.93s/it]


[0.681 0.682 0.683 0.684 0.685]


100%|██████████| 5/5 [00:31<00:00,  6.22s/it]


[0.686 0.687 0.688 0.689 0.69 ]


100%|██████████| 5/5 [00:27<00:00,  5.49s/it]


[0.691 0.692 0.693 0.694 0.695]


100%|██████████| 5/5 [00:24<00:00,  4.98s/it]


[0.696 0.697 0.698 0.699 0.7  ]


100%|██████████| 5/5 [00:24<00:00,  4.94s/it]


[0.701 0.702 0.703 0.704 0.705]


100%|██████████| 5/5 [00:35<00:00,  7.06s/it]


[0.706 0.707 0.708 0.709 0.71 ]


100%|██████████| 5/5 [00:35<00:00,  7.07s/it]


[0.711 0.712 0.713 0.714 0.715]


100%|██████████| 5/5 [00:37<00:00,  7.51s/it]


[0.716 0.717 0.718 0.719 0.72 ]


100%|██████████| 5/5 [00:22<00:00,  4.51s/it]


[0.721 0.722 0.723 0.724 0.725]


100%|██████████| 5/5 [00:39<00:00,  7.82s/it]


[0.726 0.727 0.728 0.729 0.73 ]


100%|██████████| 5/5 [00:30<00:00,  6.02s/it]


[0.731 0.732 0.733 0.734 0.735]


100%|██████████| 5/5 [00:26<00:00,  5.24s/it]


[0.736 0.737 0.738 0.739 0.74 ]


100%|██████████| 5/5 [00:25<00:00,  5.12s/it]


[0.741 0.742 0.743 0.744 0.745]


100%|██████████| 5/5 [00:25<00:00,  5.14s/it]


[0.746 0.747 0.748 0.749 0.75 ]


100%|██████████| 5/5 [00:29<00:00,  5.89s/it]


[0.751 0.752 0.753 0.754 0.755]


100%|██████████| 5/5 [00:32<00:00,  6.46s/it]


[0.756 0.757 0.758 0.759 0.76 ]


100%|██████████| 5/5 [00:28<00:00,  5.71s/it]


[0.761 0.762 0.763 0.764 0.765]


100%|██████████| 5/5 [00:31<00:00,  6.22s/it]


[0.766 0.767 0.768 0.769 0.77 ]


100%|██████████| 5/5 [00:30<00:00,  6.17s/it]


[0.771 0.772 0.773 0.774 0.775]


100%|██████████| 5/5 [00:36<00:00,  7.20s/it]


[0.776 0.777 0.778 0.779 0.78 ]


100%|██████████| 5/5 [00:23<00:00,  4.63s/it]


[0.781 0.782 0.783 0.784 0.785]


100%|██████████| 5/5 [00:29<00:00,  5.90s/it]


[0.786 0.787 0.788 0.789 0.79 ]


100%|██████████| 5/5 [00:21<00:00,  4.39s/it]


[0.791 0.792 0.793 0.794 0.795]


100%|██████████| 5/5 [00:28<00:00,  5.65s/it]


[0.796 0.797 0.798 0.799 0.8  ]


100%|██████████| 5/5 [00:20<00:00,  4.08s/it]


[0.801 0.802 0.803 0.804 0.805]


100%|██████████| 5/5 [00:30<00:00,  6.08s/it]


[0.806 0.807 0.808 0.809 0.81 ]


100%|██████████| 5/5 [00:25<00:00,  5.19s/it]


[0.811 0.812 0.813 0.814 0.815]


100%|██████████| 5/5 [00:47<00:00,  9.41s/it]


[0.816 0.817 0.818 0.819 0.82 ]


100%|██████████| 5/5 [00:28<00:00,  5.70s/it]


[0.821 0.822 0.823 0.824 0.825]


100%|██████████| 5/5 [00:40<00:00,  8.13s/it]


[0.826 0.827 0.828 0.829 0.83 ]


100%|██████████| 5/5 [00:29<00:00,  5.81s/it]


[0.831 0.832 0.833 0.834 0.835]


100%|██████████| 5/5 [00:27<00:00,  5.51s/it]


[0.836 0.837 0.838 0.839 0.84 ]


100%|██████████| 5/5 [00:37<00:00,  7.43s/it]


[0.841 0.842 0.843 0.844 0.845]


100%|██████████| 5/5 [00:37<00:00,  7.56s/it]


[0.846 0.847 0.848 0.849 0.85 ]


100%|██████████| 5/5 [00:25<00:00,  5.17s/it]


[0.851 0.852 0.853 0.854 0.855]


100%|██████████| 5/5 [00:27<00:00,  5.41s/it]


[0.856 0.857 0.858 0.859 0.86 ]


100%|██████████| 5/5 [00:31<00:00,  6.32s/it]


[0.861 0.862 0.863 0.864 0.865]


100%|██████████| 5/5 [00:24<00:00,  4.99s/it]


[0.866 0.867 0.868 0.869 0.87 ]


100%|██████████| 5/5 [00:39<00:00,  7.92s/it]


[0.871 0.872 0.873 0.874 0.875]


100%|██████████| 5/5 [00:22<00:00,  4.52s/it]


[0.876 0.877 0.878 0.879 0.88 ]


100%|██████████| 5/5 [00:30<00:00,  6.02s/it]


[0.881 0.882 0.883 0.884 0.885]


100%|██████████| 5/5 [00:39<00:00,  7.80s/it]


[0.886 0.887 0.888 0.889 0.89 ]


100%|██████████| 5/5 [00:25<00:00,  5.06s/it]


[0.891 0.892 0.893 0.894 0.895]


100%|██████████| 5/5 [00:24<00:00,  4.83s/it]


[0.896 0.897 0.898 0.899 0.9  ]


100%|██████████| 5/5 [00:22<00:00,  4.59s/it]


[0.901 0.902 0.903 0.904 0.905]


100%|██████████| 5/5 [00:35<00:00,  7.18s/it]


[0.906 0.907 0.908 0.909 0.91 ]


100%|██████████| 5/5 [00:22<00:00,  4.57s/it]


[0.911 0.912 0.913 0.914 0.915]


100%|██████████| 5/5 [00:32<00:00,  6.51s/it]


[0.916 0.917 0.918 0.919 0.92 ]


100%|██████████| 5/5 [00:41<00:00,  8.31s/it]


[0.921 0.922 0.923 0.924 0.925]


100%|██████████| 5/5 [00:24<00:00,  4.94s/it]


[0.926 0.927 0.928 0.929 0.93 ]


100%|██████████| 5/5 [00:35<00:00,  7.07s/it]


[0.931 0.932 0.933 0.934 0.935]


100%|██████████| 5/5 [00:26<00:00,  5.25s/it]


[0.936 0.937 0.938 0.939 0.94 ]


100%|██████████| 5/5 [00:43<00:00,  8.68s/it]


[0.941 0.942 0.943 0.944 0.945]


100%|██████████| 5/5 [00:33<00:00,  6.70s/it]


[0.946 0.947 0.948 0.949 0.95 ]


100%|██████████| 5/5 [00:38<00:00,  7.77s/it]


[0.951 0.952 0.953 0.954 0.955]


100%|██████████| 5/5 [00:30<00:00,  6.02s/it]


[0.956 0.957 0.958 0.959 0.96 ]


100%|██████████| 5/5 [00:36<00:00,  7.32s/it]


[0.961 0.962 0.963 0.964 0.965]


100%|██████████| 5/5 [00:37<00:00,  7.55s/it]


[0.966 0.967 0.968 0.969 0.97 ]


100%|██████████| 5/5 [00:29<00:00,  5.88s/it]


[0.971 0.972 0.973 0.974 0.975]


100%|██████████| 5/5 [00:34<00:00,  6.95s/it]


[0.976 0.977 0.978 0.979 0.98 ]


100%|██████████| 5/5 [00:34<00:00,  6.91s/it]


[0.981 0.982 0.983 0.984 0.985]


100%|██████████| 5/5 [00:22<00:00,  4.50s/it]


[0.986 0.987 0.988 0.989 0.99 ]


100%|██████████| 5/5 [00:39<00:00,  7.85s/it]


[0.991 0.992 0.993 0.994 0.995]


100%|██████████| 5/5 [00:50<00:00, 10.11s/it]


[0.996 0.997 0.998 0.999 1.   ]


100%|██████████| 5/5 [00:30<00:00,  6.17s/it]


In [60]:
cleandf_minigpt = pd.read_pickle("data/clean_minigpt.pkl")

In [61]:
random_minigpt = cleandf_minigpt.sample(3, random_state=42)

In [62]:
random_minigpt

iteration  num_beam  temperature  top_p  \
1574          0         1          1.0  0.682   
1720          0         1          1.0  0.844   
1510          0         1          1.0  0.612   

                                            description   id      model  \
1574  The image shows a woman and two children in a ...  681  MiniGPT-4   
1720  This image depicts a woman and two children st...  843  MiniGPT-4   
1510  In this image, there is a woman standing in a ...  611  MiniGPT-4   

                                                  words  \
1574  [The, Ġimage, Ġshows, Ġa, Ġwoman, Ġand, Ġtwo, ...   
1720  [This, Ġimage, Ġdepicts, Ġa, Ġwoman, Ġand, Ġtw...   
1510  [In, Ġthis, Ġimage, ,, Ġthere, Ġis, Ġa, Ġwoman...   

                                                  surps       uid  avg_info  \
1574  [3.276172161102295, 7.5474724769592285, 4.2324...  3.326710  2.377067   
1720  [4.856124401092529, 5.75446891784668, 5.188001...  4.032907  2.577611   
1510  [4.456691265106201, 2.3173508644104004, 5.3269...  4.331714  2.494707   

           ttr  avg_freq  
1574  0.520000  6.246933  
1720  0.622222  6.045778  
1510  0.485294  6.225735

In [59]:
def generate_score(text):
    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[
        {
            "role": "user",
            "content": [
            {
                "type": "text", 
                "text": "Evaluate the overall level of interestingness of this text, which is a description of a picture. Rate your evaluation from the scale of 1 to 10, with 1 being the least interesting. If there is no input text, please return your evaluation as NaN. The output should be either be a numerical value, or NaN."
            },
            {
                "type": "text", 
                "text": text
            }
            ],
        }
        ],
    )

    # data = {"description": text,
    #         "eval": response.choices[0]["message"]["content"]}
    # df = pd.DataFrame(data)

    score = response.choices[0]["message"]["content"]

    return score


In [65]:
random_minigpt['score'] = random_minigpt['description'].apply(generate_score)
random_minigpt

iteration  num_beam  temperature  top_p  \
1574          0         1          1.0  0.682   
1720          0         1          1.0  0.844   
1510          0         1          1.0  0.612   

                                            description   id      model  \
1574  The image shows a woman and two children in a ...  681  MiniGPT-4   
1720  This image depicts a woman and two children st...  843  MiniGPT-4   
1510  In this image, there is a woman standing in a ...  611  MiniGPT-4   

                                                  words  \
1574  [The, Ġimage, Ġshows, Ġa, Ġwoman, Ġand, Ġtwo, ...   
1720  [This, Ġimage, Ġdepicts, Ġa, Ġwoman, Ġand, Ġtw...   
1510  [In, Ġthis, Ġimage, ,, Ġthere, Ġis, Ġa, Ġwoman...   

                                                  surps       uid  avg_info  \
1574  [3.276172161102295, 7.5474724769592285, 4.2324...  3.326710  2.377067   
1720  [4.856124401092529, 5.75446891784668, 5.188001...  4.032907  2.577611   
1510  [4.456691265106201, 2.3173508644104004, 5.3269...  4.331714  2.494707   

           ttr  avg_freq score  
1574  0.520000  6.246933   5.7  
1720  0.622222  6.045778     6  
1510  0.485294  6.225735   5.5

In [66]:
cleandf_minigpt['score'] = cleandf_minigpt['description'].apply(generate_score)

In [67]:
cleandf_minigpt

iteration  num_beam  temperature  top_p  \
0             0         1        0.010  0.900   
1             0         1        0.012  0.900   
2             0         1        0.014  0.900   
3             0         1        0.016  0.900   
4             0         1        0.018  0.900   
...         ...       ...          ...    ...   
1842          0         1        1.000  0.987   
1843          0         1        1.000  0.991   
1844          0         1        1.000  0.993   
1845          0         1        1.000  0.994   
1846          0         1        1.000  0.997   

                                            description   id      model  \
0     The image shows a woman and two children stand...    1  MiniGPT-4   
1     The image shows a woman and two children stand...    2  MiniGPT-4   
2     The image shows a woman and two children stand...    3  MiniGPT-4   
3     The image shows a woman and two children stand...    4  MiniGPT-4   
4     The image shows a woman and two children stand...    5  MiniGPT-4   
...                                                 ...  ...        ...   
1842  In this black and white picture, there is a ma...  986  MiniGPT-4   
1843  In this image, there is a woman standing in th...  990  MiniGPT-4   
1844  The image shows a group of people, including a...  992  MiniGPT-4   
1845  This image shows a woman standing in a kitchen...  993  MiniGPT-4   
1846  There is a woman, a man, and a child in the pi...  996  MiniGPT-4   

                                                  words  \
0     [The, Ġimage, Ġshows, Ġa, Ġwoman, Ġand, Ġtwo, ...   
1     [The, Ġimage, Ġshows, Ġa, Ġwoman, Ġand, Ġtwo, ...   
2     [The, Ġimage, Ġshows, Ġa, Ġwoman, Ġand, Ġtwo, ...   
3     [The, Ġimage, Ġshows, Ġa, Ġwoman, Ġand, Ġtwo, ...   
4     [The, Ġimage, Ġshows, Ġa, Ġwoman, Ġand, Ġtwo, ...   
...                                                 ...   
1842  [In, Ġthis, Ġblack, Ġand, Ġwhite, Ġpicture, ,,...   
1843  [In, Ġthis, Ġimage, ,, Ġthere, Ġis, Ġa, Ġwoman...   
1844  [The, Ġimage, Ġshows, Ġa, Ġgroup, Ġof, Ġpeople...   
1845  [This, Ġimage, Ġshows, Ġa, Ġwoman, Ġstanding, ...   
1846  [There, Ġis, Ġa, Ġwoman, ,, Ġa, Ġman, ,, Ġand,...   

                                                  surps       uid  avg_info  \
0     [3.276172161102295, 7.5474724769592285, 4.2324...  3.748849  2.408837   
1     [3.276172161102295, 7.5474724769592285, 4.2324...  3.841741  2.414539   
2     [3.276172161102295, 7.5474724769592285, 4.2324...  4.657914  2.355983   
3     [3.276172161102295, 7.5474724769592285, 4.2324...  4.657914  2.355983   
4     [3.276172161102295, 7.5474724769592285, 4.2324...  4.657914  2.355983   
...                                                 ...       ...       ...   
1842  [4.456691265106201, 2.3173508644104004, 9.1033...  4.040512  2.361031   
1843  [4.456691265106201, 2.3173508644104004, 5.3269...  4.147193  2.482595   
1844  [3.276172161102295, 7.5474724769592285, 4.2324...  4.585183  2.490274   
1845  [4.856124401092529, 5.75446891784668, 1.815931...  3.937921  2.646942   
1846  [5.558810710906982, 1.6791528463363647, 1.2591...  4.242570  2.296197   

           ttr  avg_freq score  
0     0.528736  6.105172   5.8  
1     0.552632  5.970526   5.5  
2     0.455556  6.124889   4.5  
3     0.455556  6.124889   4.5  
4     0.455556  6.124889   4.8  
...        ...       ...   ...  
1842  0.500000  6.216308   6.2  
1843  0.533333  6.202133   5.7  
1844  0.541176  6.123412   5.5  
1845  0.705882  6.252059   6.5  
1846  0.512821  6.145385   5.5  

[1847 rows x 14 columns]

In [54]:
# random_minigpt['score'] = random_minigpt['description'].apply(generate_score)

In [55]:
# random_minigpt

iteration  num_beam  temperature  top_p  \
1574          0         1          1.0  0.682   
1720          0         1          1.0  0.844   
1510          0         1          1.0  0.612   

                                            description   id      model  \
1574  The image shows a woman and two children in a ...  681  MiniGPT-4   
1720  This image depicts a woman and two children st...  843  MiniGPT-4   
1510  In this image, there is a woman standing in a ...  611  MiniGPT-4   

                                                  words  \
1574  [The, Ġimage, Ġshows, Ġa, Ġwoman, Ġand, Ġtwo, ...   
1720  [This, Ġimage, Ġdepicts, Ġa, Ġwoman, Ġand, Ġtw...   
1510  [In, Ġthis, Ġimage, ,, Ġthere, Ġis, Ġa, Ġwoman...   

                                                  surps       uid  avg_info  \
1574  [3.276172161102295, 7.5474724769592285, 4.2324...  3.326710  2.377067   
1720  [4.856124401092529, 5.75446891784668, 5.188001...  4.032907  2.577611   
1510  [4.456691265106201, 2.3173508644104004, 5.3269...  4.331714  2.494707   

           ttr  avg_freq score  
1574  0.520000  6.246933     5  
1720  0.622222  6.045778     5  
1510  0.485294  6.225735     5

In [69]:
cleandf_minigpt.to_pickle("data/random_minigpt.pkl")