In [1]:
import os, time
import openai
import pandas as pd
import base64
import tqdm
from tqdm import tqdm
import pandas as pd
import numpy as np


In [2]:
cred_path = "../../../Desktop/others/anlp_project/openaikey.txt"
# cred_path = "../../../Desktop/others/anlp_project/miaomiao_key.txt"
image_path = "data/pic.png"

In [3]:
with open(cred_path, encoding = 'utf-8') as f:
  key = f.readline().strip()

openai.api_key = key
openai.api_key

'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'

In [4]:
# Function to encode the image
def encode_image(image_path):
  with open(image_path, "rb") as image_file:
    return base64.b64encode(image_file.read()).decode('utf-8')

# Getting the base64 string
base64_image = encode_image(image_path)

In [5]:
def generate_text(temp, top_p):
    response = openai.ChatCompletion.create(
        model="gpt-4-vision-preview",
        temperature = temp,
        top_p = top_p,
        messages=[
        {
            "role": "user",
            "content": [
            {
                "type": "text", 
                "text": "What’s in this image?"
            },
            {
                "type": "image_url", 
                "image_url": {
                "url": f"data:image/jpeg;base64,{base64_image}"}
            }
            ],
        }
        ],
        max_tokens=300,
    )

    # col = [i]
    data = {"temperature" : [temp],
            "top_p" : [top_p],
           "description": response.choices[0]["message"]["content"]
           }
    
    df = pd.DataFrame(data)

    return df
    #return response.choices[0]["message"]["content"]


In [6]:
def get_description_df(param_list, top_p):
  df = pd.DataFrame()
  for i in tqdm(param_list):
    new = generate_text(temp=i, top_p=top_p)
    df = pd.concat([df, new])
  df = df.reset_index(drop=True)
  return df

In [113]:
# temps = np.arange(0.001, 1.001, 0.001)
# tempsplit = np.array_split(temps, 20)

In [8]:
temps = np.arange(0.001, 1.001, 0.001)
tempsplit = np.array_split(temps, 200)
tempsplit[111:]


[array([0.556, 0.557, 0.558, 0.559, 0.56 ]),
 array([0.561, 0.562, 0.563, 0.564, 0.565]),
 array([0.566, 0.567, 0.568, 0.569, 0.57 ]),
 array([0.571, 0.572, 0.573, 0.574, 0.575]),
 array([0.576, 0.577, 0.578, 0.579, 0.58 ]),
 array([0.581, 0.582, 0.583, 0.584, 0.585]),
 array([0.586, 0.587, 0.588, 0.589, 0.59 ]),
 array([0.591, 0.592, 0.593, 0.594, 0.595]),
 array([0.596, 0.597, 0.598, 0.599, 0.6  ]),
 array([0.601, 0.602, 0.603, 0.604, 0.605]),
 array([0.606, 0.607, 0.608, 0.609, 0.61 ]),
 array([0.611, 0.612, 0.613, 0.614, 0.615]),
 array([0.616, 0.617, 0.618, 0.619, 0.62 ]),
 array([0.621, 0.622, 0.623, 0.624, 0.625]),
 array([0.626, 0.627, 0.628, 0.629, 0.63 ]),
 array([0.631, 0.632, 0.633, 0.634, 0.635]),
 array([0.636, 0.637, 0.638, 0.639, 0.64 ]),
 array([0.641, 0.642, 0.643, 0.644, 0.645]),
 array([0.646, 0.647, 0.648, 0.649, 0.65 ]),
 array([0.651, 0.652, 0.653, 0.654, 0.655]),
 array([0.656, 0.657, 0.658, 0.659, 0.66 ]),
 array([0.661, 0.662, 0.663, 0.664, 0.665]),
 array([0.

In [9]:
for temp in tempsplit[112:]:
    print(temp)
    df_continue = get_description_df(param_list=temp, top_p=1)
    temp_name = str(np.round(temp[-1], decimals=3))
    df_continue.to_pickle('data/temp_data_4v/df_'+temp_name+'.pkl')

[0.561 0.562 0.563 0.564 0.565]


100%|██████████| 5/5 [00:31<00:00,  6.39s/it]


[0.566 0.567 0.568 0.569 0.57 ]


100%|██████████| 5/5 [00:33<00:00,  6.79s/it]


[0.571 0.572 0.573 0.574 0.575]


100%|██████████| 5/5 [00:36<00:00,  7.35s/it]


[0.576 0.577 0.578 0.579 0.58 ]


100%|██████████| 5/5 [00:25<00:00,  5.18s/it]


[0.581 0.582 0.583 0.584 0.585]


100%|██████████| 5/5 [00:27<00:00,  5.55s/it]


[0.586 0.587 0.588 0.589 0.59 ]


100%|██████████| 5/5 [00:28<00:00,  5.71s/it]


[0.591 0.592 0.593 0.594 0.595]


100%|██████████| 5/5 [00:34<00:00,  6.86s/it]


[0.596 0.597 0.598 0.599 0.6  ]


100%|██████████| 5/5 [00:26<00:00,  5.24s/it]


[0.601 0.602 0.603 0.604 0.605]


100%|██████████| 5/5 [00:36<00:00,  7.30s/it]


[0.606 0.607 0.608 0.609 0.61 ]


100%|██████████| 5/5 [00:28<00:00,  5.68s/it]


[0.611 0.612 0.613 0.614 0.615]


100%|██████████| 5/5 [00:36<00:00,  7.31s/it]


[0.616 0.617 0.618 0.619 0.62 ]


100%|██████████| 5/5 [00:27<00:00,  5.48s/it]


[0.621 0.622 0.623 0.624 0.625]


100%|██████████| 5/5 [00:30<00:00,  6.04s/it]


[0.626 0.627 0.628 0.629 0.63 ]


100%|██████████| 5/5 [00:31<00:00,  6.21s/it]


[0.631 0.632 0.633 0.634 0.635]


100%|██████████| 5/5 [00:22<00:00,  4.48s/it]


[0.636 0.637 0.638 0.639 0.64 ]


100%|██████████| 5/5 [00:23<00:00,  4.64s/it]


[0.641 0.642 0.643 0.644 0.645]


100%|██████████| 5/5 [00:26<00:00,  5.29s/it]


[0.646 0.647 0.648 0.649 0.65 ]


100%|██████████| 5/5 [00:31<00:00,  6.28s/it]


[0.651 0.652 0.653 0.654 0.655]


100%|██████████| 5/5 [00:33<00:00,  6.60s/it]


[0.656 0.657 0.658 0.659 0.66 ]


100%|██████████| 5/5 [00:25<00:00,  5.04s/it]


[0.661 0.662 0.663 0.664 0.665]


100%|██████████| 5/5 [00:25<00:00,  5.10s/it]


[0.666 0.667 0.668 0.669 0.67 ]


100%|██████████| 5/5 [00:29<00:00,  5.80s/it]


[0.671 0.672 0.673 0.674 0.675]


100%|██████████| 5/5 [00:32<00:00,  6.42s/it]


[0.676 0.677 0.678 0.679 0.68 ]


100%|██████████| 5/5 [00:29<00:00,  5.93s/it]


[0.681 0.682 0.683 0.684 0.685]


100%|██████████| 5/5 [00:31<00:00,  6.22s/it]


[0.686 0.687 0.688 0.689 0.69 ]


100%|██████████| 5/5 [00:27<00:00,  5.49s/it]


[0.691 0.692 0.693 0.694 0.695]


100%|██████████| 5/5 [00:24<00:00,  4.98s/it]


[0.696 0.697 0.698 0.699 0.7  ]


100%|██████████| 5/5 [00:24<00:00,  4.94s/it]


[0.701 0.702 0.703 0.704 0.705]


100%|██████████| 5/5 [00:35<00:00,  7.06s/it]


[0.706 0.707 0.708 0.709 0.71 ]


100%|██████████| 5/5 [00:35<00:00,  7.07s/it]


[0.711 0.712 0.713 0.714 0.715]


100%|██████████| 5/5 [00:37<00:00,  7.51s/it]


[0.716 0.717 0.718 0.719 0.72 ]


100%|██████████| 5/5 [00:22<00:00,  4.51s/it]


[0.721 0.722 0.723 0.724 0.725]


100%|██████████| 5/5 [00:39<00:00,  7.82s/it]


[0.726 0.727 0.728 0.729 0.73 ]


100%|██████████| 5/5 [00:30<00:00,  6.02s/it]


[0.731 0.732 0.733 0.734 0.735]


100%|██████████| 5/5 [00:26<00:00,  5.24s/it]


[0.736 0.737 0.738 0.739 0.74 ]


100%|██████████| 5/5 [00:25<00:00,  5.12s/it]


[0.741 0.742 0.743 0.744 0.745]


100%|██████████| 5/5 [00:25<00:00,  5.14s/it]


[0.746 0.747 0.748 0.749 0.75 ]


100%|██████████| 5/5 [00:29<00:00,  5.89s/it]


[0.751 0.752 0.753 0.754 0.755]


100%|██████████| 5/5 [00:32<00:00,  6.46s/it]


[0.756 0.757 0.758 0.759 0.76 ]


100%|██████████| 5/5 [00:28<00:00,  5.71s/it]


[0.761 0.762 0.763 0.764 0.765]


100%|██████████| 5/5 [00:31<00:00,  6.22s/it]


[0.766 0.767 0.768 0.769 0.77 ]


100%|██████████| 5/5 [00:30<00:00,  6.17s/it]


[0.771 0.772 0.773 0.774 0.775]


100%|██████████| 5/5 [00:36<00:00,  7.20s/it]


[0.776 0.777 0.778 0.779 0.78 ]


100%|██████████| 5/5 [00:23<00:00,  4.63s/it]


[0.781 0.782 0.783 0.784 0.785]


100%|██████████| 5/5 [00:29<00:00,  5.90s/it]


[0.786 0.787 0.788 0.789 0.79 ]


100%|██████████| 5/5 [00:21<00:00,  4.39s/it]


[0.791 0.792 0.793 0.794 0.795]


100%|██████████| 5/5 [00:28<00:00,  5.65s/it]


[0.796 0.797 0.798 0.799 0.8  ]


100%|██████████| 5/5 [00:20<00:00,  4.08s/it]


[0.801 0.802 0.803 0.804 0.805]


100%|██████████| 5/5 [00:30<00:00,  6.08s/it]


[0.806 0.807 0.808 0.809 0.81 ]


100%|██████████| 5/5 [00:25<00:00,  5.19s/it]


[0.811 0.812 0.813 0.814 0.815]


100%|██████████| 5/5 [00:47<00:00,  9.41s/it]


[0.816 0.817 0.818 0.819 0.82 ]


100%|██████████| 5/5 [00:28<00:00,  5.70s/it]


[0.821 0.822 0.823 0.824 0.825]


100%|██████████| 5/5 [00:40<00:00,  8.13s/it]


[0.826 0.827 0.828 0.829 0.83 ]


100%|██████████| 5/5 [00:29<00:00,  5.81s/it]


[0.831 0.832 0.833 0.834 0.835]


100%|██████████| 5/5 [00:27<00:00,  5.51s/it]


[0.836 0.837 0.838 0.839 0.84 ]


100%|██████████| 5/5 [00:37<00:00,  7.43s/it]


[0.841 0.842 0.843 0.844 0.845]


100%|██████████| 5/5 [00:37<00:00,  7.56s/it]


[0.846 0.847 0.848 0.849 0.85 ]


100%|██████████| 5/5 [00:25<00:00,  5.17s/it]


[0.851 0.852 0.853 0.854 0.855]


100%|██████████| 5/5 [00:27<00:00,  5.41s/it]


[0.856 0.857 0.858 0.859 0.86 ]


100%|██████████| 5/5 [00:31<00:00,  6.32s/it]


[0.861 0.862 0.863 0.864 0.865]


100%|██████████| 5/5 [00:24<00:00,  4.99s/it]


[0.866 0.867 0.868 0.869 0.87 ]


100%|██████████| 5/5 [00:39<00:00,  7.92s/it]


[0.871 0.872 0.873 0.874 0.875]


100%|██████████| 5/5 [00:22<00:00,  4.52s/it]


[0.876 0.877 0.878 0.879 0.88 ]


100%|██████████| 5/5 [00:30<00:00,  6.02s/it]


[0.881 0.882 0.883 0.884 0.885]


100%|██████████| 5/5 [00:39<00:00,  7.80s/it]


[0.886 0.887 0.888 0.889 0.89 ]


100%|██████████| 5/5 [00:25<00:00,  5.06s/it]


[0.891 0.892 0.893 0.894 0.895]


100%|██████████| 5/5 [00:24<00:00,  4.83s/it]


[0.896 0.897 0.898 0.899 0.9  ]


100%|██████████| 5/5 [00:22<00:00,  4.59s/it]


[0.901 0.902 0.903 0.904 0.905]


100%|██████████| 5/5 [00:35<00:00,  7.18s/it]


[0.906 0.907 0.908 0.909 0.91 ]


100%|██████████| 5/5 [00:22<00:00,  4.57s/it]


[0.911 0.912 0.913 0.914 0.915]


100%|██████████| 5/5 [00:32<00:00,  6.51s/it]


[0.916 0.917 0.918 0.919 0.92 ]


100%|██████████| 5/5 [00:41<00:00,  8.31s/it]


[0.921 0.922 0.923 0.924 0.925]


100%|██████████| 5/5 [00:24<00:00,  4.94s/it]


[0.926 0.927 0.928 0.929 0.93 ]


100%|██████████| 5/5 [00:35<00:00,  7.07s/it]


[0.931 0.932 0.933 0.934 0.935]


100%|██████████| 5/5 [00:26<00:00,  5.25s/it]


[0.936 0.937 0.938 0.939 0.94 ]


100%|██████████| 5/5 [00:43<00:00,  8.68s/it]


[0.941 0.942 0.943 0.944 0.945]


100%|██████████| 5/5 [00:33<00:00,  6.70s/it]


[0.946 0.947 0.948 0.949 0.95 ]


100%|██████████| 5/5 [00:38<00:00,  7.77s/it]


[0.951 0.952 0.953 0.954 0.955]


100%|██████████| 5/5 [00:30<00:00,  6.02s/it]


[0.956 0.957 0.958 0.959 0.96 ]


100%|██████████| 5/5 [00:36<00:00,  7.32s/it]


[0.961 0.962 0.963 0.964 0.965]


100%|██████████| 5/5 [00:37<00:00,  7.55s/it]


[0.966 0.967 0.968 0.969 0.97 ]


100%|██████████| 5/5 [00:29<00:00,  5.88s/it]


[0.971 0.972 0.973 0.974 0.975]


100%|██████████| 5/5 [00:34<00:00,  6.95s/it]


[0.976 0.977 0.978 0.979 0.98 ]


100%|██████████| 5/5 [00:34<00:00,  6.91s/it]


[0.981 0.982 0.983 0.984 0.985]


100%|██████████| 5/5 [00:22<00:00,  4.50s/it]


[0.986 0.987 0.988 0.989 0.99 ]


100%|██████████| 5/5 [00:39<00:00,  7.85s/it]


[0.991 0.992 0.993 0.994 0.995]


100%|██████████| 5/5 [00:50<00:00, 10.11s/it]


[0.996 0.997 0.998 0.999 1.   ]


100%|██████████| 5/5 [00:30<00:00,  6.17s/it]


In [44]:
# response.choices[0]["message"]["content"]

'The image is a black and white line drawing depicting a scene in a kitchen. There are three people in the image: a woman and two children. The woman is standing by the kitchen counter, drying a plate with a towel. One child is standing on a step ladder, reaching for a cookie jar that is on top of a wall-mounted cupboard. The other child is standing on the floor, reaching up towards the first child, possibly asking for a cookie or trying to help.\n\nThe kitchen has a window with curtains, through which a tree can be seen outside. On the counter, there are various kitchen items, including a mixing bowl, a rolling pin, and some plates. There is also a sink with water overflowing onto the floor, which the woman does not seem to have noticed. The scene suggests a domestic, everyday moment with a hint of mischief and an oversight regarding the overflowing sink.'

In [43]:
# response = openai.ChatCompletion.create(
#         model="gpt-4-vision-preview",
#         messages=[
#         {
#             "role": "user",
#             "content": [
#             {
#                 "type": "text", 
#                 "text": "What’s in this image?"
#             },
#             {
#                 "type": "image_url", 
#                 "image_url": {
#                 "url": f"data:image/jpeg;base64,{base64_image}"}
#             }
#             ],
#         }
#         ],
#         max_tokens=300,
#         temperature=1,
#         top_p=0.001
#     )